language: ruby
rvm:
 - 1.9.3
 - 2.2.8
 - 2.3.5
 - jruby-19mode
 - jruby-9.1.9.0

script: "bundle exec rspec"

gemfile:
  - gemfiles/ar2.3.18.gemfile
  - gemfiles/ar3.2.22.gemfile
  - gemfiles/ar4.1.16.gemfile
  - gemfiles/ar4.2.10.gemfile
  - gemfiles/ar5.1.4.gemfile

matrix:
  exclude:
    - rvm: 2.2.4
      gemfile: gemfiles/ar2.3.18.gemfile
    - rvm: 2.3.5
      gemfile: gemfiles/ar2.3.18.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/ar2.3.18.gemfile
    - rvm: jruby-9.1.9  .0
      gemfile: gemfiles/ar2.3.18.gemfile