language: ruby
rvm:
 - 1.9.3
 - 2.2.4
 - 2.3.0
 - jruby-19mode
 - jruby-9.0.4.0

script: "bundle exec rspec"

gemfile:
  - gemfiles/ar2.3.18.gemfile
  - gemfiles/ar3.2.22.gemfile
  - gemfiles/ar4.1.14.gemfile
  - gemfiles/ar4.2.5.gemfile
  #-gemfiles/ar5.0.0.beta1.gemfile TODO support this in an extra version

matrix:
  exclude:
    - rvm: 2.2.4
      gemfile: gemfiles/ar2.3.18.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/ar2.3.18.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/ar2.3.18.gemfile
    - rvm: jruby-9.0.4.0
      gemfile: gemfiles/ar2.3.18.gemfile