language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - jruby-18mode
 - jruby-19mode
 - 2.0.0

script: "bundle exec rspec"

gemfile:
  - gemfiles/ar2.3.18.gemfile
  - gemfiles/ar3.2.14.gemfile
  - gemfiles/ar3.2.3.gemfile
  - gemfiles/ar4.0.0.gemfile
  - gemfiles/ar4.1.0.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/ar4.0.0.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/ar4.0.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/ar4.1.0.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/ar4.1.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/ar2.3.18.gemfile